# python main_ui_prmd.py recognition -c config/st_gcn/ui_prmd_cs/cls_pos/kimore_all.yaml
work_dir: ../../data/UI_PRMD/work_st_gcn/kinect/cls_4_cv
#weights: ../../data/UI_PRMD/work_st_gcn/8_2/epoch290_model.pt
# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../../data/UI_PRMD/st-gcn/kinect/cls/pos_all_4_cv/train_data.npy
  label_path: ../../data/UI_PRMD/st-gcn/kinect/cls/pos_all_4_cv/train_label.pkl
test_feeder_args:
  data_path: ../../data/UI_PRMD/st-gcn/kinect/cls/pos_all_4_cv/train_data.npy
  label_path: ../../data/UI_PRMD/st-gcn/kinect/cls/pos_all_4_cv/train_label.pkl

# model
model: net.st_gcn_ui_prmd.Model
model_args:
  in_channels: 3
  num_class: 10
  dropout: 0.5
  #dims: [45000,60,64,[256,128]]
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#opti
weight_decay: 0.0001
base_lr: 0.1
#step: [10, 50]
step: [10, 50, 100]
num_epoch: 200

# training
#device: [0,1,2,3]
device: [0,1,2,3]
batch_size: 64
test_batch_size: 64
