# python main_ui_prmd.py recognition -c config/st_gcn/ui_prmd_cs/cls_pos/kimore_all.yaml
work_dir: ../../data/UI_PRMD/work_st_gcn/kinect/cls_4_cv_bs8_1
weights: ../../data/UI_PRMD/work_st_gcn/kinect/cls_4_cv_bs8/epoch146_model.pt
# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/UI_PRMD/kinect/cls/pos_all_4_cv/train_data.npy
  label_path: ./data/UI_PRMD/kinect/cls/pos_all_4_cv/train_label.pkl
test_feeder_args:
  data_path: ./data/UI_PRMD/kinect/cls/pos_all_4_cv/train_data.npy
  label_path: ./data/UI_PRMD/kinect/cls/pos_all_4_cv/train_label.pkl

# model
model: net.st_gcn_ui_prmd.Model
model_args:
  in_channels: 3
  num_class: 10
  dropout: 0.5
  #dims: [45000,60,64,[256,128]]
  edge_importance_weighting: True
  graph_args:
    layout: 'ui_prmd'
    strategy: 'spatial'

#opti
weight_decay: 0.0001
base_lr: 0.1
#step: [10, 50]
step: [10, 50, 100]
num_epoch: 200
#start_epoch: 200
# training
#device: [0,1,2,3]
device: [0,1]
batch_size: 8
test_batch_size: 8
